[project]
authors = ["Mitchell Robert Vollger <mrvollger@gmail.com>"]
channels = ["https://conda-forge.fredhutch.org/bioconda", "https://conda-forge.fredhutch.org/conda-forge"]
channel-priority = "disabled"
description = "Add a short description here"
name = "FIRE"
platforms = ["linux-64"]
version = "0.1.1"

[system-requirements]
linux = "4.15"
libc = { family="glibc", version="2.27" }

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test-data = { cmd = [
  "cd",
  "$INIT_CWD",
  "&&",
  "mkdir",
  "-p",
  "fire-test-data",
  "&&",
  "aws",
  "s3",
  "--no-sign-request",
  "sync",
  "s3://stergachis-public1/FIRE/test-data",
  "fire-test-data/",
] }
test = { cmd = [
  "cd",
  "$INIT_CWD/fire-test-data",
  "&&",
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
  "--configfile",
  "test.yaml",
  "-k",
], depends-on = [
  "test-data",
], clean-env = true }

fire = { cmd = [
  "cd",
  "$INIT_CWD",
  "&&",
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
] }
slurm = { cmd = [
  "cd",
  "$INIT_CWD",
  "&&",
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
  "--profile",
  "$PIXI_PROJECT_ROOT/profiles/slurm-executor",
] }

[dependencies]
snakemake = "==8.21"
snakemake-executor-plugin-slurm = ">=0.11.2"
snakefmt = "*"
ruff = "*"
awscli = "2.22.*"
taplo = "*"
conda = ">=24.7"
[pypi-dependencies]
